<a href="https://colab.research.google.com/github/dilipkm007/PythonBasics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

<h1>Scalar</h1>

In [3]:
s = 5
s

5

<h1>Vector</h1>

In [4]:
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

<h1>Matrix</h1>

In [5]:
m = np.array([[5, 12, 6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

<h1>Check DataType of declared variable</h1>

In [6]:
type(s)

int

In [7]:
type(v)

numpy.ndarray

In [8]:
type(m)

numpy.ndarray

<h3>Another way to create scalar in python<\h3>

In [9]:
s_array = np.array(5)
s_array

array(5)

In [10]:
type(s_array)

numpy.ndarray

<h1>Data Shape</h1>

In [11]:
v.shape

(3,)

In [12]:
m.shape

(2, 3)

In [13]:
s_array.shape

()

<h1>Creating new vector, Matrix using Reshape</h1>

In [14]:
v.reshape(1, 3)

array([[ 5, -2,  4]])

In [15]:
v.reshape(3, 1)

array([[ 5],
       [-2],
       [ 4]])